name: onion CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: install flex
          run: sudo apt install -y flex bison
        - name: install mil
          run: wget -O mil_run https://www.cs.ucr.edu/~dtan004/prac3/mil_run && chmod +x mil_run && sudo mv mil_run /usr/local/bin
        - name: make
          run: cd src && make
        - name: run test
          run: cd src && ./ci_basis
